In [41]:
import numpy as np
import math


array = np.arange(0, 128, 1).reshape((2, 2, 2, 2, 2, 2, 2)) #создание тензора размерности 7
array -= np.arange(127, -1, -1).reshape((2, 2, 2, 2, 2, 2, 2)) #математическая операция над тензором 
print(array.shape) #размерность тензора
print(array.dtype) #тип данных тензора
array #вывод результата


(2, 2, 2, 2, 2, 2, 2)
int64


array([[[[[[[-127, -125],
            [-123, -121]],

           [[-119, -117],
            [-115, -113]]],


          [[[-111, -109],
            [-107, -105]],

           [[-103, -101],
            [ -99,  -97]]]],



         [[[[ -95,  -93],
            [ -91,  -89]],

           [[ -87,  -85],
            [ -83,  -81]]],


          [[[ -79,  -77],
            [ -75,  -73]],

           [[ -71,  -69],
            [ -67,  -65]]]]],




        [[[[[ -63,  -61],
            [ -59,  -57]],

           [[ -55,  -53],
            [ -51,  -49]]],


          [[[ -47,  -45],
            [ -43,  -41]],

           [[ -39,  -37],
            [ -35,  -33]]]],



         [[[[ -31,  -29],
            [ -27,  -25]],

           [[ -23,  -21],
            [ -19,  -17]]],


          [[[ -15,  -13],
            [ -11,   -9]],

           [[  -7,   -5],
            [  -3,   -1]]]]]],





       [[[[[[   1,    3],
            [   5,    7]],

           [[   9,   11],
            [  13,   15]]]

In [16]:
E = np.eye(3) #создание единичной матрицы
M = np.array([[8, 32, 47], [7, 22, 81], [63, 91, 5]]) #создание матрицы
print("Сложение матрицы со скаляром: ", M + 5*E, sep='\n') #Сложение матрицы со скаляром по правилам линейной алгебры
print("Почленное сложение элементов матрицы со скаляром: ", M + 5, sep='\n') #Почленное сложение элементов матрицы со скаляром


Сложение матрицы со скаляром: 
[[13. 32. 47.]
 [ 7. 27. 81.]
 [63. 91. 10.]]
Почленное сложение элементов матрицы со скаляром: 
[[13 37 52]
 [12 27 86]
 [68 96 10]]


In [33]:
M = np.array([[8, 32, 47], [7, 22, 81], [63, 91, 5]])
print("Матрица:", M, sep="\n")
print("Определитель матрицы:", np.linalg.det(M)) #нахождение оприделителя матрицы
print("Проверка методом разложения миноров:")
M11, M12, M13 = M[0, 0], M[0, 1], M[0, 2] #получение элементов с помощью индексирования
print(f'M11, M12, M13: {M[0, 0]}, {M[0, 1]}, {M[0, 2]}')
#нахождение миноров с помощью индексирования
det11, det12, det13 = math.floor(np.linalg.det(M[1:,1:])), math.floor(np.linalg.det(M[1:, [0, 2]])), math.floor(np.linalg.det(M[1:, :2]))
print(f'det11, det12, det13: {np.linalg.det(M[1:,1:])}, {np.linalg.det(M[1:, [0, 2]])}, {np.linalg.det(M[1:, :2])}')
print(f'M11*det11 - M12*det12 + M13*det13 = {M11*det11 - M12*det12 + M13*det13}') #нахождение определителя с помощью разложения по минорам
print('68885 = 68885 => всё чётенько') #вывод


Матрица:
[[ 8 32 47]
 [ 7 22 81]
 [63 91  5]]
Определитель матрицы: 68885.0
Проверка методом разложения миноров:
M11, M12, M13: 8, 32, 47
det11, det12, det13: -7260.999999999999, -5067.999999999999, -748.9999999999998
M11*det11 - M12*det12 + M13*det13 = 68885
68885 = 68885 => всё чётенько


In [37]:
array = np.array([20, 7, 2, 7, 1, 8, 32, 1, 5, 2, 6, 2, 7, 8, 11, 73, 26, 17, 81, 30, 13, 7, 17, 3, 82, 11, 5, 4], dtype = np.float64)
#мин-макс нормализация
array -= min(array) 
array /= (max(array) - min(array))
np.set_printoptions(precision=3)
array


array([0.235, 0.074, 0.012, 0.074, 0.   , 0.086, 0.383, 0.   , 0.049,
       0.012, 0.062, 0.012, 0.074, 0.086, 0.123, 0.889, 0.309, 0.198,
       0.988, 0.358, 0.148, 0.074, 0.198, 0.025, 1.   , 0.123, 0.049,
       0.037])

In [51]:
array = np.array([20, 7, 2, 7, 1, 8, 32, 1, 5, 2, 6, 2, 7, 8, 11, 73, 26, 17, 81, 30, 13, 7, 17, 3, 82, 11, 5, 4], dtype = np.float64).reshape((7, 4))
print(array)
print("среднеарифметическое каждого ряда:", array.mean(axis=0))
print("среднеарифметическое каждой строкт:", array.mean(axis=1))

[[20.  7.  2.  7.]
 [ 1.  8. 32.  1.]
 [ 5.  2.  6.  2.]
 [ 7.  8. 11. 73.]
 [26. 17. 81. 30.]
 [13.  7. 17.  3.]
 [82. 11.  5.  4.]]
среднеарифметическое каждого ряда: [22.     8.571 22.    17.143]
среднеарифметическое каждой строкт: [ 9.   10.5   3.75 24.75 38.5  10.   25.5 ]
